Fix BaseEncryptedField commit 86602c5
Commit 86602c5 results in an error:
UnboundLocalError: local variable 'max_length' referenced before
assignment

This commit fixes this.